config/routes.rb
Beta1::Application.routes.draw do
  
  get "products/index"
  get "karvy/index"
  get "camsfeeds/index"
  get "setup/c80"
  get "setup/rgess"
  get "setup/bonds"
  get "setup/emergency"
  get "setup/gold"
  get "setup/justinvest"
  get "setup/house"
  get "setup/marriage"
  get "setup/education"
  get "transactions/s"
  post "transactions/s"
  get "transactions/holdings"
  get "transactions/ru"
  post "transactions/ru"
  post "transactions/confirmation"
  get "banks/mandate"
  resources :visitors
  resources :analyses
  resources :taxsavings
  resources :dashboards do 
    collection do
      get :investment
    end
  end
  resources :funds 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :kyc
  resources :banks
  resources :transactions do 
    collection do
      post :create_multiple

    end
  end

  resources :camsfeeds do 
    collection do 
      post :import
    end
  end

  resources :products do
 collection {post :import}
  end

  get "static_pages/index"
  get "static_pages/home"
  get "static_pages/whyus"
  get "static_pages/aboutus"
  get "static_pages/setup"
  get "static_pages/productpage"
  get "static_pages/download_pdf1"
  get "static_pages/download_pdf2"
  get "static_pages/download_pdf3"
  get "static_pages/download_pdf4"
  get "static_pages/video"
  get "dashboards/show"
  get "static_pages/videotreasure"
  get "static_pages/dashboard"

  root :to => 'static_pages#index'

  

end

app/models/kyc.rb
class Kyc < ActiveRecord::Base
	belongs_to :user

	validates_presence_of :first_name
	validates_presence_of :last_name
	validates_presence_of :father_spouse_name
	validates_presence_of :nationality
	validates_presence_of :pan
	validates_format_of :pan, :with => /\A([A-Za-z]{5}\d{4}[A-Za-z]{1})\Z/i 
	validates_presence_of :c_house_no
	validates_presence_of :c_street_name
	validates_presence_of :c_area_name
	validates_presence_of :correspondence_city_town_village
	validates_presence_of :correspondence_state
	validates_presence_of :correspondence_postal_code
	validates_presence_of :correspondence_email
	validates_presence_of :p_house_no
	validates_presence_of :p_street_name
	validates_presence_of :p_area_name
	validates_presence_of :permanent_city_town_village
	validates_presence_of :permanent_state
	validates_presence_of :permanent_postal_code
	validates_presence_of :permanent_email
	validates_format_of :permanent_postal_code, :with => /\A(\d{6})\Z/i 
	validate :permanent_landline_or_mobile
	validates_format_of :permanent_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 
	
	validates_format_of :correspondence_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 
	validates_format_of :correspondence_postal_code, :with => /\A(\d{6})\Z/i 
	validate :correspondence_landline_or_mobile
	def correspondence_landline_or_mobile
	  if [self.correspondence_landline, self.correspondence_mobile].reject(&:blank?).size == 0
	    errors[:base] << ("Please fill either landline no. or mobile no.")
	  end
	end 
	def permanent_landline_or_mobile
	  if [self.permanent_landline, self.permanent_landline].reject(&:blank?).size == 0
	    errors[:base] << ("Please fill either landline no. or mobile no.")
	  end
	end 

end

app/controllers/kycs_controller.rb
class KycsController < ApplicationController

	def new
	 
	  if current_user.kyc_status != 1
	  	@kyc = current_user.build_kyc	
	  else
	  	 @kyc = current_user.kyc
	  end

	end


	
	def create
	    
	    @kyc = current_user.build_kyc(kyc_params)
	    @kyc.user_id = current_user.id
	    if @kyc.same == true
	    	@kyc.p_house_no = @kyc.c_house_no
	    	@kyc.p_street_name = @kyc.c_street_name
	    	@kyc.p_area_name = @kyc.c_area_name
	    	@kyc.permanent_state = @kyc.correspondence_state
	    	@kyc.permanent_city_town_village = @kyc.correspondence_city_town_village
	    	@kyc.permanent_country =@kyc.correspondence_country
	    	@kyc.permanent_landline = @kyc.correspondence_landline
	    	@kyc.permanent_mobile = @kyc.correspondence_mobile
	    	@kyc.permanent_email = @kyc.correspondence_email
	    	@kyc.permanent_postal_code = @kyc.correspondence_postal_code
	    end	
		if @kyc.save
	      current_user.kyc_status = 1
	      current_user.save
	      redirect_to dashboards_show_path
	    else
	      render :action => 'new'
	    end
	      
  	end
		
  	def update
       @kyc = current_user.kyc
       @kyc.update_attributes(kyc_params)
       redirect_to dashboards_show_path  
   end

  private
	  def kyc_params
	    params.require(:kyc).permit(:first_name,:last_name,:father_spouse_name,:gender,:marital_status,:date_of_birth,
	     :nationality,:residence_status, :pan, :proof_of_identity, :c_house_no, :c_street_name, :c_area_name, :correspondence_city_town_village,
	     :correspondence_state, :correspondence_country,:correspondence_postal_code,:correspondence_landline,
	     :correspondence_mobile,:correspondence_email, :correspondence_proof_of_address,:same,:p_house_no, :p_street_name, :p_area_name,
	     :permanent_city_town_village,:permanent_state,:permanent_country, :permanent_postal_code, :permanent_landline,
	     :permanent_mobile, :permanent_email, :permanent_proof_of_address,:annual_income, :occupation, :pep_status)
	    

	  end

end

app/helpers/kycs_helper.rb
module KycsHelper
end

app/views/kycs/new.html.erb
 <script type="text/javascript"> 
$(document).ready(function() {
    $('#checkbox1').change(function() {
        $('#checkboxresult').toggle();
    });
});

 </script>
<%= simple_form_for @kyc , url: kyc_path, html: {class: 'form-horizontal' } do |f| %>
			
  <h2>Personal Information</h2>
  	
  	<%= f.input :first_name , label:'First Name'%>
	<%= f.input :last_name , label:'Last Name' %>
	<%= f.input :father_spouse_name , label:'Father/Spouse Name' %>
	<%= f.input :marital_status, label:'Marital Status',collection: [ "Single", "Married"],:include_blank => false %>
	<%= f.input :gender , label:'Gender',collection: [ "Male", "Female"],:include_blank => false %>
	<%= f.input :date_of_birth, label:'Date of Birth', as: :date, start_year: Date.today.year - 90,
                              end_year: Date.today.year - 13%>
	<%= f.input :nationality, label:'Nationality', input_html: { value: 'Indian' } %>
	<%= f.input :residence_status, label:'Residence Status',collection: [ "Resident", "Non-resident","Foreign National"],:include_blank => false %>
	<%= f.input :pan , label:'PAN' %>
	<%= f.input :proof_of_identity, label:'Proof of Identity',collection: [ "UID(Aadhar)", "Passport","Voter ID","Driving License","PAN Card","Others"],:include_blank => false %>
	 <%= f.input :annual_income, label:'Annual Income',collection: [ "Below 1 Lac", "1-5 Lacs","5-10 Lacs","10-25 Lacs"," >25 Lacs"],:include_blank => false %>
	<%= f.input :occupation, label:'Occupation',collection: [ "Service","Business","Student","Household",       "Professional","Farmer","Retired","Others"],:include_blank => false %>
	<%= f.input :pep_status, label:'PEP Status',hint: 'Politically Exposed Person',collection: [ "None", "Politically Exposed Person (PEP)","Related to a Politically Exposed Person (PEP)"],:include_blank => false%>

	<h2>Address Information</h2>

	<h4>Correspondence Address</h4>
	<%= f.input :c_house_no, label:'House Number' %>
	<%= f.input :c_street_name, label:'Street Name' %>
	<%= f.input :c_area_name, label:'Area Name' %>
	<%= f.input :correspondence_city_town_village, label:'City' ,collection: ["Agra",	"Ahmedabad",	"Ajmer",	"Allahabad",	"Amritsar",	"Anand",	"Asansol",	"Aurangabad",	"Bangalore",	"Baroda",	"Bharuch",	"Bhavnagar",	"Bhopal",	"Bhubaneswar",	"Calicut",	"Chandigarh",	"Chennai",	"Coimbatore",	"Dehradun",	"Dharwad",	"Dubai",	"Durgapur",	"Erode",	"Guntur",	"Guwahati",	"Hubli",	"Hyderabad",	"Indore",	"Jaipur",	"Jalandhar",	"Jalgaon",	"Jamnagar",	"Jamshedpur",	"Jodpur",	"Kanpur",	"Karaikudi",	"Kochi",	"Kolkata",	"Kota",	"Kottayam",	"Lucknow",	"Ludhiana",	"Mangalore",	"Meerut",	"Moradabad",	"Mumbai",	"Mysore",	"Nagpur",	"Nasik",	"New Delhi",	"Panjim",	"Patna",	"Pondicherry",	"Pune",	"Raipur",	"Rajahmundry",	"Rajkot",	"Ranchi",	"Salem",	"Siliguri",	"Surat",	"Tirunelveli",	"Tirupur",	"Trichy",	"Trivandrum",	"Udaipur",	"Varanasi",	"Vashi",	"Vijayawada",	"Others"] %>
	<%= f.input :correspondence_state, label:'State',collection: ["Andhra Pradesh",	"Arunachal Pradesh",	"Assam",	"Bihar",	"Chandigarh",	"Delhi",	"Goa",	"Gujarat",	"Haryana",	"Himachal Pradesh",	"Jammu And Kashmir",	"Karnataka",	"Kerala",	"Madhya Pradesh",	"Maharashtra",	"Manipur",	"Meghalaya",	"Mizoram",	"Nagaland",	"Orissa",	"Punjab",	"Rajasthan",	"Tamil Nadu",	"Tripura",	"Uttar Pradesh",	"West Bengal",	"Others"] %>
	<%= f.input :correspondence_country, label:'Country' ,priority: [ "India" ] %>
	<%= f.input :correspondence_postal_code, label:'Postal Code' %>
	<%= f.input :correspondence_landline, label:'Landline no.' %>
	<%= f.input :correspondence_mobile, label:'Mobile no.',hint: 'Please fill either landline no. or mobile no.' %>
	<%= f.input :correspondence_email, label:'Email id' %>
	<%= f.input :correspondence_proof_of_address, label:'Proof of Address',collection: [ "Passport", "Ration Card","Registered Lease / Sale Agreement of Residence","Driving License","Voter Identity Card","Latest Bank Account Statement/Passbook", "Latest Telephone Bill (only Land Line)","Latest Electricity Bill","Latest Gas Bill","Others(Not more than 3 months old)"],:include_blank => false %>

    
	<%=f.input :same, hint:'Permanent Address is same as correspondence address', input_html: { id: 'checkbox1' }, label: false,value:true %>
   <div id="checkboxresult" >
    


	<h4>Permanent Address</h4>
	<%= f.input :p_house_no, label:'House Number' %>
	<%= f.input :p_street_name, label:'Street Name' %>
	<%= f.input :p_area_name, label:'Area Name' %>
	<%= f.input :permanent_city_town_village, label:'City',collection: ["Agra",	"Ahmedabad",	"Ajmer",	"Allahabad",	"Amritsar",	"Anand",	"Asansol",	"Aurangabad",	"Bangalore",	"Baroda",	"Bharuch",	"Bhavnagar",	"Bhopal",	"Bhubaneswar",	"Calicut",	"Chandigarh",	"Chennai",	"Coimbatore",	"Dehradun",	"Dharwad",	"Dubai",	"Durgapur",	"Erode",	"Guntur",	"Guwahati",	"Hubli",	"Hyderabad",	"Indore",	"Jaipur",	"Jalandhar",	"Jalgaon",	"Jamnagar",	"Jamshedpur",	"Jodpur",	"Kanpur",	"Karaikudi",	"Kochi",	"Kolkata",	"Kota",	"Kottayam",	"Lucknow",	"Ludhiana",	"Mangalore",	"Meerut",	"Moradabad",	"Mumbai",	"Mysore",	"Nagpur",	"Nasik",	"New Delhi",	"Panjim",	"Patna",	"Pondicherry",	"Pune",	"Raipur",	"Rajahmundry",	"Rajkot",	"Ranchi",	"Salem",	"Siliguri",	"Surat",	"Tirunelveli",	"Tirupur",	"Trichy",	"Trivandrum",	"Udaipur",	"Varanasi",	"Vashi",	"Vijayawada",	"Others"] %>
	<%= f.input :permanent_state, label:'State',collection: ["Andhra Pradesh",	"Arunachal Pradesh",	"Assam",	"Bihar",	"Chandigarh",	"Delhi",	"Goa",	"Gujarat",	"Haryana",	"Himachal Pradesh",	"Jammu And Kashmir",	"Karnataka",	"Kerala",	"Madhya Pradesh",	"Maharashtra",	"Manipur",	"Meghalaya",	"Mizoram",	"Nagaland",	"Orissa",	"Punjab",	"Rajasthan",	"Tamil Nadu",	"Tripura",	"Uttar Pradesh",	"West Bengal",	"Others"] %>
	<%= f.input :permanent_country, label:'Country'  ,priority: [ "India" ] %>
	<%= f.input :permanent_postal_code, label:'Postal Code' %>
	<%= f.input :permanent_landline, label:'Landline no.' %>
	<%= f.input :permanent_mobile, label:'Mobile no.',hint: 'Please fill either landline no. or mobile no.' %>
	<%= f.input :permanent_email, label:'Email id' %>
	<%= f.input :permanent_proof_of_address, label:'Proof of Address',collection: [ "Passport", "Ration Card","Registered Lease / Sale Agreement of Residence","Driving License","Voter Identity Card","Latest Bank Account Statement/Passbook", "Latest Telephone Bill (only Land Line)","Latest Electricity Bill","Latest Gas Bill","Others(Not more than 3 months old)"],:include_blank => false %>
</div>

	
  <p><%= f.submit "Save" %></p>
  
<% end %>



	