config/routes.rb
Beta1::Application.routes.draw do
  
  get "products/index"
  get "karvy/index"
  get "camsfeeds/index"
  get "setup/c80"
  get "setup/rgess"
  get "setup/bonds"
  get "setup/emergency"
  get "setup/gold"
  get "setup/justinvest"
  get "setup/house"
  get "setup/marriage"
  get "setup/education"
  get "transactions/s"
  post "transactions/s"
  get "transactions/holdings"
  get "transactions/ru"
  post "transactions/ru"
  post "transactions/confirmation"
  get "banks/mandate"
  resources :visitors
  resources :analyses
  resources :taxsavings
  resources :dashboards do 
    collection do
      get :investment
    end
  end
  resources :funds 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :kyc
  resources :banks
  resources :transactions do 
    collection do
      post :create_multiple

    end
  end

  resources :camsfeeds do 
    collection do 
      post :import
    end
  end

  resources :products do
 collection {post :import}
  end

  get "static_pages/index"
  get "static_pages/home"
  get "static_pages/whyus"
  get "static_pages/aboutus"
  get "static_pages/setup"
  get "static_pages/productpage"
  get "static_pages/download_pdf1"
  get "static_pages/download_pdf2"
  get "static_pages/download_pdf3"
  get "static_pages/download_pdf4"
  get "static_pages/video"
  get "dashboards/show"
  get "static_pages/videotreasure"
  get "static_pages/dashboard"

  root :to => 'static_pages#index'

  

end

app/models/analysis.rb
class Analysis < ActiveRecord::Base
self.inheritance_column = nil
end

app/models/bank.rb
class Bank < ActiveRecord::Base
	belongs_to :user
	has_many :transactions

	validates_presence_of :name_of_bank ,:bank_account_num , :bank_account_type ,:bank_mode_of_holding,
	 :bank_first_holder,:bank_branch_address, :bank_city, :bank_ifsc_code, :bank_micr_code

  def umrn_no
    "URMN-%.8d" % id
  end
end

app/models/camsfeed.rb
class Camsfeed < ActiveRecord::Base




def self.import(file)
  allowed_attributes = [ "amc_code","folio_no","prodcode","scheme","inv_name","trxntype","trxnno","trxnmode",	"trxnstat",
  	"usercode",	"usrtrxno",	"traddate",	"postdate",	"purprice",	"units",	"amount",	"brokcode",	"subbrok"	,"brokperc",
  	"brokcomm",	"altfolio"	,"rep_date",	"time1",	"trxnsubtyp",	"application_no",	"trxn_nature",	"tax",	"total_tax",
  	"te_15h",	"micr_no",	"remarks",	"swflag",	"old_folio",	"seq_no",	"reinvest_flag",	"mult_brok",	"stt",	"location",
  	"scheme_type",	"tax_status",	"load",	"scanrefno",	"pan",	"inv_iin"	,"targ_src_scheme",	"trxn_type_flag",
  	"ticob_trtype",	"ticob_trno",	"ticob_posted_date",	"dp_id",	"trxn_charges",	"eligib_amt",	"src_of_txn",	"trxn_suffix",
  	"siptrxnno",	"ter_location",	"euin",	"euin_valid",	"euin_opted",	"sub_brk_arn"]
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    camsfeed = Camsfeed.new
    camsfeed.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
    camsfeed.save!
  end
end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end


end

app/models/freekyc.rb
class Freekyc < ActiveRecord::Base

	validates_presence_of :name
	validates_presence_of :phone_number
	validates_presence_of :email
	validates_presence_of :pan
	validates_format_of :pan, :with => /\A([A-Za-z]{5}\d{4}[A-Za-z]{1})\Z/i 
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 
end

app/models/fund.rb
class Fund < ActiveRecord::Base
	has_many :transactions
	has_many :holdings


end

app/models/holding.rb
class Holding < ActiveRecord::Base
	belongs_to :user
	belongs_to :fund
	belongs_to :transaction
end

app/models/karvyfeed.rb
class Karvyfeed < ActiveRecord::Base
end

app/models/karvyfeedcon.rb
class Karvyfeedcon < ActiveRecord::Base
end

app/models/kyc.rb
class Kyc < ActiveRecord::Base
	belongs_to :user

	validates_presence_of :first_name
	validates_presence_of :last_name
	validates_presence_of :father_spouse_name
	validates_presence_of :nationality
	validates_presence_of :pan
	validates_format_of :pan, :with => /\A([A-Za-z]{5}\d{4}[A-Za-z]{1})\Z/i 
	validates_presence_of :c_house_no
	validates_presence_of :c_street_name
	validates_presence_of :c_area_name
	validates_presence_of :correspondence_city_town_village
	validates_presence_of :correspondence_state
	validates_presence_of :correspondence_postal_code
	validates_presence_of :correspondence_email
	validates_presence_of :p_house_no
	validates_presence_of :p_street_name
	validates_presence_of :p_area_name
	validates_presence_of :permanent_city_town_village
	validates_presence_of :permanent_state
	validates_presence_of :permanent_postal_code
	validates_presence_of :permanent_email
	validates_format_of :permanent_postal_code, :with => /\A(\d{6})\Z/i 
	validate :permanent_landline_or_mobile
	validates_format_of :permanent_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 
	
	validates_format_of :correspondence_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 
	validates_format_of :correspondence_postal_code, :with => /\A(\d{6})\Z/i 
	validate :correspondence_landline_or_mobile
	def correspondence_landline_or_mobile
	  if [self.correspondence_landline, self.correspondence_mobile].reject(&:blank?).size == 0
	    errors[:base] << ("Please fill either landline no. or mobile no.")
	  end
	end 
	def permanent_landline_or_mobile
	  if [self.permanent_landline, self.permanent_landline].reject(&:blank?).size == 0
	    errors[:base] << ("Please fill either landline no. or mobile no.")
	  end
	end 

end

app/models/msgfrompg.rb
class Msgfrompg < ActiveRecord::Base
end

app/models/msgtopg.rb
class Msgtopg < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	

	def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

	

	def self.import(file)
		allowed_attributes=["name","relased_on","price"]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
     # product = find_by_id(row["id"]) || new
     product=Product.new
      #product.attributes = row.to_hash.slice(*accessible_attributes)
      product.attributes=row.to_hash.select{|k,v| allowed_attributes.include? k }
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/models/taxsaving.rb
class Taxsaving < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :phone_number
	validates_presence_of :email
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to :user
	belongs_to :bank
	belongs_to :fund
	has_one :holding

	

  def ord_num
    "RV-%.8d" % id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :banks
  has_many :transactions
  has_many :holdings
  has_one :kyc
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  
def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(first_name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
    end
    user
end

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	

	def investment
		@funds = Fund.find(params[:fund_ids])
		
		
	end
	def show
	end
	



end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/karvy_helper.rb
module KarvyHelper
end

app/helpers/kycs_helper.rb
module KycsHelper
end

app/views/dashboards/investment.html.erb
<script type="text/javascript">
$(document).ready(function () {
$("#txn").change(function(){
  if ($("#txn").val()=="SIP") {$("#sip").show(); }
  if ($("#txn").val()=="Lumpsum") {$("#sip").hide();  }
  
})

});



</script>

<%= form_tag create_multiple_transactions_path do %>
Select Bank <%= select_tag "bankid", options_from_collection_for_select(current_user.banks, "id", "name_of_bank") %><br>
<% @funds.each do |fund| %>
<%= fund.scheme_name %><br>	
<%= hidden_field_tag "transactions[][user_id]", current_user.id %>
<%= hidden_field_tag "transactions[][fund_id]", fund.id %>
Amount(in Rs.) <%= number_field_tag "transactions[][amount]", fund.min_investment %><br>

Transaction Type :<%= select_tag "transactions[][transaction_type]", options_for_select(["Lumpsum","SIP"]),:id => "txn" %><br>

<% holdings_amc = current_user.holdings.where(:amc_code => fund.amc_code) %>
<% if holdings_amc.exists? %>
<% f_folio = holdings_amc.first.folio %>
<% else %>
<% f_folio = 'New' %>
<% end %>
<% if fund.fund_type == "Dividend" %>
Dividend Option :<%= select_tag "transactions[][dividend_option]", options_for_select(["Reinvest","Payout"]) %><br>
<% end %>
Folio :<%= select_tag "transactions[][folio_id]",options_for_select([f_folio])%><br>
<div id="sip" style="display: none;">
Investment Date :<%= date_field_tag "transactions[][t_date]"%><br>
No. of months :<%= number_field_tag "transactions[][sip_months]" %><br>
</div>
<%= hidden_field_tag "transactions[][transaction_status]", "PrePayement" %>
----------------------------------------------------------------------------------------------------------------------
<br>

<% end %>
<%= submit_tag "Do Transaction" %>
<% end %>	

app/views/dashboards/show.html.erb

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span3">
			<ul class="nav nav-list">
				<li class="nav-header">
					Dashboard
				</li>
				<li class="active">
					<%= link_to "Products Page", static_pages_productpage_path %>
				</li>
				<li>
					<%= link_to "Try Demo", static_pages_setup_path %>
				</li>
				<li>
					<%= link_to "KYC", new_kyc_path %>
				</li>
				<li>
					 <%= link_to "Funds", funds_path %>
				</li>
				<% if current_user.try(:admin?) %>
				<li>
					<%= link_to "Mandate", banks_mandate_path(format: "xls") %>
				</li>
				<% end %>
				<li class="nav-header">
					Banks
				</li>
				<li>
					  <% for bank in current_user.banks %>
					  <%= link_to " #{bank.name_of_bank}" , bank_path(bank.id) %>
					  <%= link_to "Edit #{bank.name_of_bank}" , edit_bank_path(bank.id) %>
						<% end %>
				</li>
				<li>
					 <%= link_to "Add a Bank", new_bank_path %>
				</li>
				<li class="divider">
				</li>
				<li>
					<%= link_to "Profile", edit_user_registration_path %>
				</li>
			</ul>
		</div>
		<div class="span9">
			<div class="hero-unit">
				<h2 style = "text-align:center">
					Hello <%= current_user.first_name %>,
				</h2>
				<p style = "text-align:justify">
					<br>

					
					Welcome to RupeeVest! We promise you, we will make your financial life easier. <br>

					Please check out our teaser videos to understand the revolution RupeeVest are bringing in the Indian financial services. No more agents, no more paperwork.<br>

					We will be up and live soon. Once live, we will find you and we will help you. :-)<br>
				</p>

				<div class="flex-video widescreen" style="margin: 0 auto;text-align:center;">
			      <iframe width="320" height="280" frameborder ="1"  style="border:solid rgb(37,56,60) 25px" src="//www.youtube.com/embed/DqrN2kWPzPo?rel=0" frameborder="0" allowfullscreen></iframe>
			      <iframe width="320" height="280" frameborder ="1"  style="border:solid rgb(37,56,60) 25px" src="//www.youtube.com/embed/e3Se-2rGSww?rel=0" frameborder="0" allowfullscreen></iframe>
			    </div>

			</div>
		</div>
	</div>
</div>