config/routes.rb
Beta1::Application.routes.draw do
  
  get "products/index"
  get "karvy/index"
  get "camsfeeds/index"
  get "setup/c80"
  get "setup/rgess"
  get "setup/bonds"
  get "setup/emergency"
  get "setup/gold"
  get "setup/justinvest"
  get "setup/house"
  get "setup/marriage"
  get "setup/education"
  get "transactions/s"
  post "transactions/s"
  get "transactions/holdings"
  get "transactions/ru"
  post "transactions/ru"
  post "transactions/confirmation"
  get "banks/mandate"
  resources :visitors
  resources :analyses
  resources :taxsavings
  resources :dashboards do 
    collection do
      get :investment
    end
  end
  resources :funds 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :kyc
  resources :banks
  resources :transactions do 
    collection do
      post :create_multiple

    end
  end

  resources :camsfeeds do 
    collection do 
      post :import
    end
  end

  resources :products do
 collection {post :import}
  end

  get "static_pages/index"
  get "static_pages/home"
  get "static_pages/whyus"
  get "static_pages/aboutus"
  get "static_pages/setup"
  get "static_pages/productpage"
  get "static_pages/download_pdf1"
  get "static_pages/download_pdf2"
  get "static_pages/download_pdf3"
  get "static_pages/download_pdf4"
  get "static_pages/video"
  get "dashboards/show"
  get "static_pages/videotreasure"
  get "static_pages/dashboard"

  root :to => 'static_pages#index'

  

end

app/models/analysis.rb
class Analysis < ActiveRecord::Base
self.inheritance_column = nil
end

app/models/bank.rb
class Bank < ActiveRecord::Base
	belongs_to :user
	has_many :transactions

	validates_presence_of :name_of_bank ,:bank_account_num , :bank_account_type ,:bank_mode_of_holding,
	 :bank_first_holder,:bank_branch_address, :bank_city, :bank_ifsc_code, :bank_micr_code

  def umrn_no
    "URMN-%.8d" % id
  end
end

app/models/camsfeed.rb
class Camsfeed < ActiveRecord::Base




def self.import(file)
  allowed_attributes = [ "amc_code","folio_no","prodcode","scheme","inv_name","trxntype","trxnno","trxnmode",	"trxnstat",
  	"usercode",	"usrtrxno",	"traddate",	"postdate",	"purprice",	"units",	"amount",	"brokcode",	"subbrok"	,"brokperc",
  	"brokcomm",	"altfolio"	,"rep_date",	"time1",	"trxnsubtyp",	"application_no",	"trxn_nature",	"tax",	"total_tax",
  	"te_15h",	"micr_no",	"remarks",	"swflag",	"old_folio",	"seq_no",	"reinvest_flag",	"mult_brok",	"stt",	"location",
  	"scheme_type",	"tax_status",	"load",	"scanrefno",	"pan",	"inv_iin"	,"targ_src_scheme",	"trxn_type_flag",
  	"ticob_trtype",	"ticob_trno",	"ticob_posted_date",	"dp_id",	"trxn_charges",	"eligib_amt",	"src_of_txn",	"trxn_suffix",
  	"siptrxnno",	"ter_location",	"euin",	"euin_valid",	"euin_opted",	"sub_brk_arn"]
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    camsfeed = Camsfeed.new
    camsfeed.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
    camsfeed.save!
  end
end

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end


end

app/models/freekyc.rb
class Freekyc < ActiveRecord::Base

	validates_presence_of :name
	validates_presence_of :phone_number
	validates_presence_of :email
	validates_presence_of :pan
	validates_format_of :pan, :with => /\A([A-Za-z]{5}\d{4}[A-Za-z]{1})\Z/i 
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 
end

app/models/fund.rb
class Fund < ActiveRecord::Base
	has_many :transactions
	has_many :holdings


end

app/models/holding.rb
class Holding < ActiveRecord::Base
	belongs_to :user
	belongs_to :fund
	belongs_to :transaction
end

app/models/karvyfeed.rb
class Karvyfeed < ActiveRecord::Base
end

app/models/karvyfeedcon.rb
class Karvyfeedcon < ActiveRecord::Base
end

app/models/kyc.rb
class Kyc < ActiveRecord::Base
	belongs_to :user

	validates_presence_of :first_name
	validates_presence_of :last_name
	validates_presence_of :father_spouse_name
	validates_presence_of :nationality
	validates_presence_of :pan
	validates_format_of :pan, :with => /\A([A-Za-z]{5}\d{4}[A-Za-z]{1})\Z/i 
	validates_presence_of :c_house_no
	validates_presence_of :c_street_name
	validates_presence_of :c_area_name
	validates_presence_of :correspondence_city_town_village
	validates_presence_of :correspondence_state
	validates_presence_of :correspondence_postal_code
	validates_presence_of :correspondence_email
	validates_presence_of :p_house_no
	validates_presence_of :p_street_name
	validates_presence_of :p_area_name
	validates_presence_of :permanent_city_town_village
	validates_presence_of :permanent_state
	validates_presence_of :permanent_postal_code
	validates_presence_of :permanent_email
	validates_format_of :permanent_postal_code, :with => /\A(\d{6})\Z/i 
	validate :permanent_landline_or_mobile
	validates_format_of :permanent_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 
	
	validates_format_of :correspondence_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 
	validates_format_of :correspondence_postal_code, :with => /\A(\d{6})\Z/i 
	validate :correspondence_landline_or_mobile
	def correspondence_landline_or_mobile
	  if [self.correspondence_landline, self.correspondence_mobile].reject(&:blank?).size == 0
	    errors[:base] << ("Please fill either landline no. or mobile no.")
	  end
	end 
	def permanent_landline_or_mobile
	  if [self.permanent_landline, self.permanent_landline].reject(&:blank?).size == 0
	    errors[:base] << ("Please fill either landline no. or mobile no.")
	  end
	end 

end

app/models/msgfrompg.rb
class Msgfrompg < ActiveRecord::Base
end

app/models/msgtopg.rb
class Msgtopg < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	

	def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

	

	def self.import(file)
		allowed_attributes=["name","relased_on","price"]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
     # product = find_by_id(row["id"]) || new
     product=Product.new
      #product.attributes = row.to_hash.slice(*accessible_attributes)
      product.attributes=row.to_hash.select{|k,v| allowed_attributes.include? k }
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/models/taxsaving.rb
class Taxsaving < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :phone_number
	validates_presence_of :email
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to :user
	belongs_to :bank
	belongs_to :fund
	has_one :holding

	

  def ord_num
    "RV-%.8d" % id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :banks
  has_many :transactions
  has_many :holdings
  has_one :kyc
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, :omniauth_providers => [:google_oauth2]
  
def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first

    unless user
        user = User.create(first_name: data["name"],
             email: data["email"],
             password: Devise.friendly_token[0,20]
            )
    end
    user
end

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController


def index
	@visitor = Visitor.new
 	@funds = Fund.all

end


def show
	@visitor = Visitor.new
	@fund = Fund.find(params[:id])
	
end




end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/karvy_helper.rb
module KarvyHelper
end

app/helpers/kycs_helper.rb
module KycsHelper
end

app/helpers/setup_helper.rb
module SetupHelper
end

app/views/funds/index.html.erb
 <head>
  <title>Rupeevest</title>
<script type="text/javascript">
  
 
  $(document).ready(function () {
     
   oTable = $('#funds12').dataTable({
        "bJQueryUI": true


    }).yadcf([{
        column_number: 0,
         filter_type: "auto_complete" ,
        text_data_delimiter: ","
    }, {
        column_number: 1,
        filter_container_id: "external_filter_container"
    }, {
        column_number: 2,
        filter_type: "range_number_slider"
    }, {
        column_number: 3
    }
    ]);


     
});



 





  $(document).ready(function () {

  


     
    oTable = $('#funds13').dataTable({
        "bJQueryUI": true

    }).yadcf([{
        column_number: 0,
         filter_type: "auto_complete" ,
        text_data_delimiter: ","
    }, {
        column_number: 1,
        filter_container_id: "external_filter_container2"
    }
    ]);


     
});

</script>

<script>
 $('#myTab a').click(function (e) {
  e.preventDefault();
  $(this).tab('show');
})
</script>









</head>
<h1> Funds</h1>
<ul class="nav nav-tabs" id="myTab">

  <li ><a href="#snapshot" data-toggle="tab" class = "active">Snapshot</a></li>
  <li><a href="#performance" data-toggle="tab">Performance</a></li>
</ul>
 
<div class="tab-content">
  <div class="tab-pane  active" id="snapshot">



      <div class ="span5" id="external_filter_container_wrapper">
        <label>Category:</label>
        <div id="external_filter_container"></div>
      </div>
      <div class = "span5">
        
           
            
      </div>
      
<%= form_tag investment_dashboards_path, :method => :get  do %> 
    <table id = "funds12" class="display">
<thead>
  <tr>
    <th>Fund Name</th>
    <th>Category</th>
    <th>Average AUM</th>
    <th>Fund Type</th>
    <th>Expense Ratio</th>
    <th>Check</th>
  </tr>
</thead>
<tbody>
  <% @funds.each do |fund| %>
    <tr>
      <td><%= link_to "#{fund.scheme_name}", fund_path(fund.id) %></td>
      <td><%= fund.category %></td>
      <td><%= fund.net_assets %></td>
      <td><%= fund.fund_type %></td>
      <td><%= fund.expense_ratio %></td>
       <td>
        <%= check_box_tag "fund_ids[]", fund.id %>

</td> 
    </tr>
  <% end %>
 </tbody>

</table>
 <%= submit_tag "yeah" %>   
  <% end %> 



  </div>
  <div class="tab-pane" id="performance">
<div class ="span5" id="external_filter_container_wrapper">
        <label>Category:</label>
        <div id="external_filter_container2"></div>
      </div>
      <div class = "span5">
       
      </div>
     <%= form_tag investment_dashboards_path, :method => :get  do %> 
    <table id = "funds13" class="display">
<thead>
  <tr>
    <th>Fund Name</th>
    <th>Category</th>
    <th>YTD return</th>
     <th>3M return</th>
    <th>1yr return</th> 
    <th>3yr return</th>
    <th>5yr return</th>
    <th>10yr return</th>
    <th>Check</th>
  </tr>
</thead>
<tbody>
  <% @funds.each do |fund| %>
    <tr>
      <td><%= link_to "#{fund.scheme_name}", fund_path(fund.id) %></td>
      <td><%= fund.category %></td>
      <td><%= fund.fund_ytd %></td>
      <td><%= fund.fund_3month %></td>
      <td><%= fund.fund_1year %></td>
      <td><%= fund.fund_3year %></td>
      <td><%= fund.fund_5year %></td>
      <td><%= fund.fund_10year %></td>
     <td> <%= check_box_tag "fund_ids[]", fund.id %></td> 
    </tr>
  <% end %>
 </tbody>

</table>
<%= submit_tag "yeah" %>
<% end %>



 
  </div>

</div>


app/views/funds/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rupeevest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
  
  
</head>
<script type="text/javascript">

 
 

        $(document).ready(function () {
 
            var fund_data = [
                [1, <%= @fund.fund_ytd %>],
                [2, <%= @fund.fund_3month %>],
                [3, <%= @fund.fund_1year %>],
                [4, <%= @fund.fund_3year %>],
                [5, <%= @fund.fund_5year %>]
            ];
            var category_data = [
                [1, <%= @fund.category_ytd %>],
                [2, <%= @fund.category_3month %>],
                [3, <%= @fund.category_1year %>],
                [4, <%= @fund.category_3year %>],
                [5, <%= @fund.category_5year %>]
            ];
             var benchmark_data = [
                [1, <%= @fund.benchmark_ytd %>],
                [2, <%= @fund.benchmark_3month %>],
                [3, <%= @fund.benchmark_1year %>],
                [4, <%= @fund.benchmark_3year %>],
                [5, <%= @fund.benchmark_5year %>]
            ];
 
            var data = [
                {label: "<%= @fund.scheme_name %>", data: fund_data, bars: {fillColor: "#336600"}, color: "#336600"},
                {label: "<%= @fund.category %>", data: category_data, bars: {fillColor: "#E41B17"}, color: "#E41B17"},
                {label: "<%= @fund.benchmark %>", data: category_data, bars: {fillColor: "#0000FF"}, color: "#0000FF"}
            ];
            var options = {
                xaxis: {
                    min: 0,
                    max: 7,
                    mode: null,
                    ticks: [
                        [1, "YTD"],
                        [2, "6M Return"],
                        [3, "1YR Return"],
                        [4, "3YR Return"],
                        [5, "5Yr Return"]
                    ],
                    tickLength: 0,
                    axisLabel: " Tenure (in years)",
                    axisLabelUseCanvas: true,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: "Verdana, Arial, Helvetica, Tahoma, sans-serif",
                    axisLabelPadding: 5
                }, yaxis: {
                    axisLabel: "Annualized return (in %age)",
                    tickDecimals: 0,
                    axisLabelUseCanvas: true,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: "Verdana, Arial, Helvetica, Tahoma, sans-serif",
                    axisLabelPadding: 5
                }, grid: {
                    hoverable: true,
                    clickable: false,
                    borderWidth: 1
                }, legend: {
                    labelBoxBorderColor: "none",
                    position: "right"
                }, series: {
                    shadowSize: 1,
                    bars: {
                        show: true,
                        barWidth: 0.25,
                        order: 1
                    }
                }
            };
 
            $.plot($("#placeholder"), data, options);
 




 			var fund_data2 = [
                [1, <%= @fund.holdings1_asset %>],
                [2, <%= @fund.holdings2_asset %>],
                [3, <%= @fund.holdings3_asset %>],
                [4, <%= @fund.holdings4_asset %>],
                [5, <%= @fund.holdings5_asset %>]
            ];
          
 
            var data2 = [
                {label: "<%= @fund.scheme_name %>", data: fund_data2, bars: {fillColor: "#336600"}, color: "#336600"}
            ];
            var options2 = {
                xaxis: {
                    min: 0,
                    max: 7,
                    mode: null,
                    ticks: [
                        [1, "<%= @fund.holdings1_company %>"],
                        [2, "<%= @fund.holdings2_company %>"],
                        [3, "<%= @fund.holdings3_company %>"],
                        [4, "<%= @fund.holdings4_company %>"],
                        [5, "<%= @fund.holdings5_company %>"]
                    ],
                    tickLength: 0,
                    axisLabel: "Companies",
                    axisLabelUseCanvas: true,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: "Verdana, Arial, Helvetica, Tahoma, sans-serif",
                    axisLabelPadding: 5
                }, yaxis: {
                    axisLabel: "PErcentage of total assets ",
                    tickDecimals: 0,
                    axisLabelUseCanvas: true,
                    axisLabelFontSizePixels: 12,
                    axisLabelFontFamily: "Verdana, Arial, Helvetica, Tahoma, sans-serif",
                    axisLabelPadding: 5
                }, grid: {
                    hoverable: true,
                    clickable: false,
                    borderWidth: 1
                }, legend: {
                    labelBoxBorderColor: "none",
                    position: "right"
                }, series: {
                    shadowSize: 1,
                    bars: {
                        show: true,
                        barWidth: 0.25,
                        order: 1
                    }
                }
            };
 
            $.plot($("#placeholder2"), data2, options2);
 
        });







</script>

    <style type="text/css">
        #placeholder {
            width: 800px;
            height: 500px;
            position: relative;
            margin: 0 auto;
        }
 
        .legend table, .legend > div {
            height: 82px !important;
            opacity: 1 !important;
            top: 10px;
            right: 10px;
            width: 116px !important;
        }
 
        .legend table {
            border-spacing: 5px;
            border: 1px solid #555;
            padding: 2px;
        }
         #placeholder2 {
            width: 800px;
            height: 600px;
            position: relative;
            margin: 0 auto;
        }
    </style>


<body id="bodyshowfund">

	    
	<div id="sidebar">
				
				<!-- <div id="logo"> <a href="/"><img src="img/logo.svg" alt="logo" /></a> </div> -->
				<nav id="nav" >
					<ul class="nav nav-pills" id= "sidebarelements" >
					<li><a href="#" class="scroller" data-section="#generaldetails" id="sidebarelement"><font color="#fff">General Details</font></a></li>
					<br>
	                    <li><a href="#" class="scroller" data-section="#performance" id="sidebarelement"><font color="#fff">Performance</font></a></li>
                    <br>                    
                    <li><a href="#" class="scroller" data-section="#investmentdetails" id="sidebarelement"><font color="#fff">Investment Details</font></a></li>
                    <br>
                    <li><a href="#" class="scroller" data-section="#risk" id="sidebarelement"><font color="#fff">Risk</font></a></li>
					</ul>
				</nav><!-- /nav -->
			</div>






    <!-- end Navbar -->


    
    <!-- #intro -->
	<div class="container" >
		<center><h1><%= @fund.scheme_name %> Snapshot</h1></center>
		<div class="container" id="generaldetails">	
			<div class = "container" >
				<h3>General Details</h3>
			<div class="row span5">
				<table class="table table-striped table-bordered">
				  <tr>
				  	<td>Scheme Name</td>
				  	<td><%= @fund.scheme_name %></td>
				  </tr>
				  <tr>
				  	<td>Growth NAV (Rs)</td>
				  	<td><%= @fund.growth_nav %></td>
				  </tr>
				  <tr>
				  	<td>Dividend NAV (Rs)</td>
				  	<td><%= @fund.dividend_nav %></td>
				  </tr>
				  <tr>
				  	<td>Category</td>
				  	<td><%= @fund.category %></td>
				  </tr>
				  <tr>
				  	<td>Colour Code</td>
				  	<td><%= @fund.colour_code %></td>
				  </tr>
				  

				</table>
			</div>
			<div class="row  span5">
				<table class="table table-striped table-bordered">
				  <tr>
				  	<td>Benchmark</td>
				  	<td><%= @fund.benchmark %></td>
				  </tr>
				  <tr>
				  	<td>Launch Date</td>
				  	<td>
				  	</td>
				  </tr>
				  <tr>
				  	<td>Net Assets</td>
				  	<td><%= @fund.net_assets %> cr</td>
				  </tr>
				  <tr>
				  	<td>Exit Load</td>
				  	<td><%= @fund.exit_load %></td>
				  </tr>
				  <tr>
				  	<td>Expense Ratio</td>
				  	<td><%= @fund.expense_ratio %>%</td>
				  </tr>
				</table>
			</div>
		</div>
	</div>
    <!-- ends Intro -->


    
    
     <!-- #about -->
<div class="container" id="performance">	
			<div class = "container">
				<h3>Performance</h3>
			<div class="row span8 center offset1">
				<table class="table table-striped table-bordered">
					<thead>
						<tr>
							<th></th>
							<th>YTD</th>
							<th>1 month</th>
							<th>3 month</th>
							<th>1 year</th>
							<th>3 year</th>
							<th>5 year</th>
							<th>10 year</th>
						</tr>
					</thead>
					<tbody>
				  <tr>
				  	<td>Fund</td>
				  	<td><%= @fund.fund_ytd %></td>
				  	<td><%= @fund.fund_1month %></td>
				  	<td><%= @fund.fund_3month %></td>
				  	<td><%= @fund.fund_1year %></td>
				  	<td><%= @fund.fund_3year %></td>
				  	<td><%= @fund.fund_5year %></td>
				  	<td><%= @fund.fund_10year %></td>
				  </tr>
				  <tr>
				  	<td><%= @fund.benchmark %></td>
				  	<td><%= @fund.benchmark_ytd %></td>
				  	<td><%= @fund.benchmark_1month %></td>
				  	<td><%= @fund.benchmark_3month %></td>
				  	<td><%= @fund.benchmark_1year %></td>
				  	<td><%= @fund.benchmark_3year %></td>
				  	<td><%= @fund.benchmark_5year %></td>
				  	<td><%= @fund.benchmark_10year %></td>
				  </tr>
				  <tr>
				  	<td>Category</td>
				  	<td><%= @fund.category_ytd %></td>
				  	<td><%= @fund.category_1month %></td>
				  	<td><%= @fund.category_3month %></td>
				  	<td><%= @fund.category_1year %></td>
				  	<td><%= @fund.category_3year %></td>
				  	<td><%= @fund.category_5year %></td>
				  	<td><%= @fund.category_10year %></td>
				  </tr>
				  <tr>
				  	<td>Rank within Category</td>
				  	<td><%= @fund.rank_ytd %></td>
				  	<td><%= @fund.rank_1month %></td>
				  	<td><%= @fund.rank_3month %></td>
				  	<td><%= @fund.rank_1year %></td>
				  	<td><%= @fund.rank_3year %></td>
				  	<td><%= @fund.rank_5year %></td>
				  	<td><%= @fund.rank_10year %></td>
				  </tr>
				  <tr>
				  	<td>Number of funds in Category</td>
				  	<td><%= @fund.no_of_fund_ytd %></td>
				  	<td><%= @fund.no_of_fund_1month %></td>
				  	<td><%= @fund.no_of_fund_3month %></td>
				  	<td><%= @fund.no_of_fund_1year %></td>
				  	<td><%= @fund.no_of_fund_3year %></td>
				  	<td><%= @fund.no_of_fund_5year %></td>
				  	<td><%= @fund.no_of_fund_10year %></td>
				  </tr>
				  </tbody>

				</table>
			</div>
		</div>
	</div>
     <!-- ends About -->
  
            <div >
					<br><br>
					<div id="placeholder"></div>
					
				</div>
      <!-- #team -->    
<div class="container" id="investmentdetails">
	<div class="container">
		<h3>Investment Details</h3>
		
			<div class="row span5">
				<h3>Amount</h3>
				<table class="table table-striped table-bordered">
				  <tr>
				  	<td>Minimum Investment (Rs)</td>
				  	<td><%= @fund.min_investment %></td>
				  	
				  </tr>
				  <tr>
				  	<td>Minimum SIP Investment (Rs)</td>
				  	<td><%= @fund.min_sip_investment %></td>
				  	
				  </tr>
				  <tr>
				  	<td>Minimum no. of chqs</td>
				  	<td><%= @fund.min_sip_chqs %></td>
				  	
				  </tr>
				  <tr>
				  	<td>Exit Load</td>
				  	<td><%= @fund.exit_load %></td>
				  	
				  </tr>
				</table>
			</div>
			
			<div class="row span5">
				<h3>Eligibility</h3>
				<table class="table table-striped table-bordered">
				  <tr>
				  	<td>Indian</td>
				  	<td>Yes</td>
				  	
				  </tr>
				  <tr>
				  	<td>NRI</td>
				  	<td>Db entry req</td>
				  	
				  </tr>
				  <tr>
				  	<td>HUF</td>
				  	<td>Yes</td>
				  	
				  </tr>
				  
				</table>
			</div>
		</div>
	</div>
      <!-- End Team -->  
       	
            <div >
					<br><br>
					<div id="placeholder2"></div>
					
				</div>
	
      <!-- #contact -->   	
	<div class="container" id="risk">
	<div class="container">
		<h3>Risk</h3>	
		<div class="row span8 center offset2">
				<table class="table table-striped table-bordered">
				  <tr>
				  	<td>Colour Code</td>
				  	<td>Risk Rating</td>
				   	
				  	
				  </tr>
				  <tr>
				  	<td><%= @fund.colour_code %></td>
				  	<td><% if @fund.colour_code == "Brown" %>High Risk<%end%>
				  		<% if @fund.colour_code == "Yellow" %>Medium Risk<%end%>
				  		<% if @fund.colour_code == "Blue" %>Low Risk<%end%>
				  		</td>
				  	
				  	
				  </tr>
				  
				  

				</table>
			</div>
		
	
				
	</div>
	<%= link_to 'Back', {:action => 'index'} %>
</div>   <!-- End Contact -->  
</div>




</body>


<script>
$(function () {
    $(window).scroll(function(){
    // global scroll to top button
        if ($(this).scrollTop() > 300) {
            $('.scrolltop').fadeIn();
        } else {
            $('.scrolltop').fadeOut();
        }        
    });
    
    // scroll nav
    $('.scroller').click(function(){
    	var section = $($(this).data("section"));
    	var top = section.offset().top-82;
        $("html, body").animate({ scrollTop: top }, 700);
        return false;
    });


});
</script>
