config/routes.rb
Beta1::Application.routes.draw do
  
  get "products/index"
  get "karvy/index"
  get "camsfeeds/index"
  get "setup/c80"
  get "setup/rgess"
  get "setup/bonds"
  get "setup/emergency"
  get "setup/gold"
  get "setup/justinvest"
  get "setup/house"
  get "setup/marriage"
  get "setup/education"
  get "transactions/s"
  post "transactions/s"
  get "transactions/holdings"
  get "transactions/ru"
  post "transactions/ru"
  post "transactions/confirmation"
  get "banks/mandate"
  resources :visitors
  resources :analyses
  resources :taxsavings
  resources :dashboards do 
    collection do
      get :investment
    end
  end
  resources :funds 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :kyc
  resources :banks
  resources :transactions do 
    collection do
      post :create_multiple

    end
  end

  resources :camsfeeds do 
    collection do 
      post :import
    end
  end

  resources :products do
 collection {post :import}
  end

  get "static_pages/index"
  get "static_pages/home"
  get "static_pages/whyus"
  get "static_pages/aboutus"
  get "static_pages/setup"
  get "static_pages/productpage"
  get "static_pages/download_pdf1"
  get "static_pages/download_pdf2"
  get "static_pages/download_pdf3"
  get "static_pages/download_pdf4"
  get "static_pages/video"
  get "dashboards/show"
  get "static_pages/videotreasure"
  get "static_pages/dashboard"

  root :to => 'static_pages#index'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
	

	def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

	

	def self.import(file)
		allowed_attributes=["name","relased_on","price"]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
     # product = find_by_id(row["id"]) || new
     product=Product.new
      #product.attributes = row.to_hash.slice(*accessible_attributes)
      product.attributes=row.to_hash.select{|k,v| allowed_attributes.include? k }
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::CSV.new(file.path)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  @products = Product.order(:name)
  respond_to do |format|
    format.html
    format.csv { send_data @products.to_csv }
    format.xls # { send_data @products.to_csv(col_sep: "\t") }
  end
end
  
  def import
    Product.import(params[:file])
    redirect_to products_index_url, notice: "Products imported."
  end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="container" style="background:white;">

<h1>Products</h1>

<p>
  Download:
  <%= link_to "CSV", products_path(format: "csv") %> |
  <%= link_to "Excel", products_path(format: "xls") %>
</p>

<table id="products">
  <tr>
    <th>Product Name</th>
    <th>Release Date</th>
    <th>Price</th>
  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.released_on.try("%B %e, %Y") %></td>
    <td><%= number_to_currency(product.price) %></td>
  </tr>
<% end %>
</table>

<h2>Import Products</h2>

<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
</div>

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <!-- <Cell><Data ss:Type="String">ID</Data></Cell> -->
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Release Date</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <!-- <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell> -->
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.released_on %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.price %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>